development: &devconf
    bind:
      master:
        # ipaddr_external: '1.2.3.4' # if use a special ip for master for any slave (optional)
        user:            'globodns'
        host:            'master'
        ipaddr:          '192.168.0.100'
        port:            53
        rndc_port:       953
        chroot_dir:      '/var/named/chroot'
        zones_dir:       '/etc/named'
        named_conf_file: '/etc/named/named.conf'  # must be inside zones_dir
        named_conf_link: '/etc/named.conf'  # can be anywhere
        export_chroot_dir:    <%= Rails.root.join('tmp', 'named', 'chroot_master') %>

      slaves:
        - user:             'globodns'
          host:             'slave0' ### empty means you don't have slave
          ipaddr:           '192.168.0.101'
          port:             5354
          rndc_port:        5954
          chroot_dir:       '/var/named/chroot'
          zones_dir:        '/etc/named'
          named_conf_file:  '/etc/named/named.conf'  # must be inside zones_dir
          named_conf_link:  '/etc/named.conf'  # can be anywhere
          export_chroot_dir: <%= Rails.root.join('tmp', 'named', 'chroot_slave1') %>
          # masters_external_ip: true # if slave use a different ip for communicate to master, this setting should be set to true

        - user:             'globodns'
          host:             'slave1' ### empty means you don't have slave
          ipaddr:           '192.168.0.102'
          port:             5354
          rndc_port:        5954
          chroot_dir:       '/var/named/chroot'
          zones_dir:        '/etc/named'
          named_conf_file:  '/etc/named/named.conf'  # must be inside zones_dir
          named_conf_link:  '/etc/named.conf'  # can be anywhere
          export_chroot_dir: <%= Rails.root.join('tmp', 'named', 'chroot_slave2') %>
          # masters_external_ip: true # if slave use a different ip for communicate to master, this setting should be set to true

    bind_user:                   'named'
    bind_group:                  'named'


    bind_error_log:         '/var/named/chroot_master/var/log/globodns.error.log'

    rndc_config_file:       '/etc/rndc.conf'
    rndc_key_name:          'rndc-key'

    named_conf_file:        'named.conf'
    zones_dir:              'zones'
    zones_file:             'zones.conf'
    reverse_dir:            'reverse'
    reverse_file:           'reverse.conf'
    slaves_dir:             'slaves'
    slaves_file:            'slaves.conf'
    forwards_dir:           'forwards'
    forwards_file:          'forwards.conf'
    views_file:             'views.conf'
    subdir_depth:           3

    record_order:           [ SOA, NS, MX, A, AAAA, CNAME, LOC, SPF, SRV, PTR, TXT ]
    git_author:             'Globo DNS API <dnsapi@yourdomain.com>'
    export_delay:           300  # in seconds
    mail_recipients:        [ 'Root <root@hostname.com>' ]
    dns_group: 'Internal'
    binaries:
        bind:          '/usr/sbin/named'
        named:         '/usr/sbin/named'
        rndc:          '/usr/sbin/rndc'
        rndc_confgen:  '/usr/sbin/rndc-confgen'
        checkconf:     '/usr/sbin/named-checkconf'
        dig:           '/usr/bin/dig'
        ip:            '/sbin/ip'
        git:           '/usr/bin/git'
        zone2sql:      '/usr/bin/zone2sql'
        rsync:         '/usr/bin/rsync'
        sudo:          '/usr/bin/sudo'
        chroot:        '/usr/sbin/chroot'

test:
    bind_master_user:            <%= ENV['USER'] %>
    bind_master_host:            'localbindmaster'
    bind_master_ipaddr:          '127.0.0.1'
    bind_master_port:            5353
    bind_master_rndc_port:       5953
    bind_master_chroot_dir:      <%= Rails.root.join('test', 'mock', 'chroot_master') %>
    bind_master_zones_dir:       '/etc/named'
    bind_master_named_conf_file: '/etc/named.conf'

    bind_slave_user:             'bind'
    bind_slave_host:             'localbindslave'
    bind_slave_ipaddr:           '127.0.0.1'
    bind_slave_port:             5354
    bind_slave_rndc_port:        5954
    bind_slave_chroot_dir:      <%= Rails.root.join('test', 'mock', 'chroot_slave') %>
    bind_slave_zones_dir:        '/etc/named'
    bind_slave_named_conf_file:  '/etc/named.conf'

    bind_user:                   'bind'
    bind_group:                  'bind'

    export_master_chroot_dir:    <%= Rails.root.join('test', 'mock', 'exported_chroot_master') %>
    export_slave_chroot_dir:     <%= Rails.root.join('test', 'mock', 'exported_chroot_slave') %>

    rndc_config_file:       '/etc/rndc.conf'
    rndc_key_name:          'rndc-key'

    named_conf_file:        'named.conf'
    zones_dir:              'zones'
    zones_file:             'zones.conf'
    reverse_dir:            'reverse'
    reverse_file:           'reverse.conf'
    slaves_dir:             'slaves'
    slaves_file:            'slaves.conf'
    views_file:             'views.conf'
    subdir_depth:           3

    record_order:           [ SOA, NS, MX, A, AAAA, CNAME, LOC, SPF, SRV, PTR, TXT ]
    git_author:             'Globo DNS API <dnsapi@yourdomain.com>'
    export_delay:           300  # in seconds
    mail_recipients:        [ 'Root <root@hostname.com>' ]
    dns_group:              'Internal'

    binaries:
        bind:          '/usr/sbin/named'
        named:         '/usr/sbin/named'
        rndc:          '/usr/sbin/rndc'
        rndc_confgen:  '/usr/sbin/rndc-confgen'
        checkconf:     '/usr/sbin/named-checkconf'
        dig:           '/usr/bin/dig'
        ip:            '/sbin/ip'
        git:           '/usr/bin/git'
        zone2sql:      '/usr/bin/zone2sql'
        rsync:         '/usr/bin/rsync'
        sudo:          '/usr/bin/sudo'
        chroot:        '/usr/sbin/chroot'

production: *devconf
